### ISSUE TITLE
Null pointer when used as bundle or compiled

### ISSUE THREAD

**Issue by phil294** [DjDeveloperr/deno-canvas#19]
Hello,

thanks for this tool, it works great! But not when bundled:

```js
import { createCanvas, loadImage } from "https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/master/mod.ts"

let canvas = createCanvas(200, 200)
let ctx = canvas.getContext("2d")
let img = await loadImage('img.jpg')
ctx.drawImage(img, 0, 0)
```
It works fine as `deno run script.js`. But when I `deno bundle script.js bundle.js` and `deno run bundle.js` or `deno compile script.js` (which presumably internally also calls `deno bundle` and `./script`, I get

```
rror: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    data = await Deno.readFile(url);
           ^
    at deno:core/01_core.js:101:46
    at unwrapOpResult (deno:core/01_core.js:121:13)
    at async open (deno:runtime/js/40_files.js:51:17)
    at async Object.readFile (deno:runtime/js/40_read_file.js:20:18)
    at async loadImage (https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/master/src/canvas.ts:30:12)
    at async file:///b/test/positions-map.deno.js:5:11
```
Any idea why that could be? And how to solve it? Is it a Deno bug and should be reported there?

Thanks!

**Comment by DjDeveloperr** [comment]
Looks like a bug in deno bundler (which uses SWC). I'll look into this after my last exam which is tomorrow

**Comment by jtoppine** [comment]
Yes, it's most likely related to https://github.com/denoland/deno/issues/12086

As a workaround, I found this works for me. Create your own module where you re-export canvas functions like below, and use those exports. To be honest I arrived at this solution by trial and error, and have very little idea how and why it works :)

```

import * as canvasInternal from 'https://deno.land/x/canvas/src/canvas.ts';

export const canvas = await canvasInternal.init();
export const canvasImpl = canvasInternal;
export const createCanvas = canvasInternal.createCanvas;

export const loadImage = async function(url) {
    let data;
    if (url instanceof Uint8Array) {
      data = url;
    } else if (url.startsWith("http")) {
      data = await fetch(url).then((e) => e.arrayBuffer()).then((e) =>
        new Uint8Array(e)
      );
    } else {
      data = await Deno.readFile(url);
    }
    const img = canvas.MakeImageFromEncoded(data);
    if (!img) throw new Error("Invalid image data");
    return img;
}


```

**Comment by lino-levan** [comment]
This issue should be closed as this was an issue with deno (and deno has patched this issue in newer versions.

I should note that unfortunately [the bug being fixed by this pull request](https://github.com/denoland/deno/pull/15672) is currently affecting a lot of `deno compile` runs right now, so even though the original issue is fixed, `deno compile` might not work until this is merged and released.
