### ISSUE TITLE
RuntimeError: table index is out of bounds

### ISSUE THREAD

**Issue by BlackGlory** [DjDeveloperr/deno-canvas#39]
The library seems to be unable to recycle the memory of images, it will crash if the total size of images loaded exceeds 2GB.

```ts
import { loadImage } from 'https://deno.land/x/canvas@v1.4.1/mod.ts'
import { findAllFilenames } from 'npm:extra-filesystem@0.5.1'

let size = 0
try {
  for await (const filename of findAllFilenames('input')) {
    const stat = await Deno.stat(filename)
    await loadImage(filename)
    size += stat.size
  }
} catch (e) {
  console.error(e)
  console.log(`size: ${size}`)
}
```

```
RuntimeError: table index is out of bounds
    at <anonymous> (wasm://wasm/01b26af2:1:2812125)
    at <anonymous> (wasm://wasm/01b26af2:1:2712812)
    at <anonymous> (wasm://wasm/01b26af2:1:5312829)
    at <anonymous> (wasm://wasm/01b26af2:1:890213)
    at Object._decodeImage (eval at Uc (https://deno.land/x/canvas@v1.4.1/src/lib.js:4504:15), <anonymous>:9:10)
    at Object.a.MakeImageFromEncoded (https://deno.land/x/canvas@v1.4.1/src/lib.js:1488:25)
    at loadImage (https://deno.land/x/canvas@v1.4.1/src/canvas.ts:33:22)   
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async main.ts:8:5
size: 2139342932
```

**Comment by BlackGlory** [comment]
Solved: Just call the `image.delete()` method.
